### ISSUE TITLE
Transfer of ViennaRNA PyPI ownership

### ISSUE THREAD

**Issue by RaumZeit** [ayaanhossain/ViennaRNA#7] opened 2023-06-10 13:19 UTC
Dear Ayaan Hossain,

I wonder whether you are willing to transfer ownership and maintainership of the PyPI ViennaRNA package project to us as the upstream development team.

You haven't been updating this repository since May 2022 and it seems you even provide a sort of pre-release. From what I can see at the moment, there is no easy way to tell whether you include the official upstream releases into your PyPI package or whether you patch them to some extent.

We believe it makes much more sense if we integrate submissions and updates to PyPI into our regular release workflow instead. This will ensure that all updates that are released with new versions of the ViennaRNA Package find their way into the PyPI package within a reasonable time. At the same time it would avoid any confusions of our users who don't know that the PyPI package is not maintained by us.

Please let me know about your decision.

Best,

Ronny

**Comment by ayaanhossain** [comment] 2023-06-10 13:51
Hi Ronny, thanks for reaching out. Yes, I usually only try to maintain the latest version. I last updated the 2.5.0 version and since then there's been 2.5.1 and now 2.6.0. I can consider transferring ownership of the name in PyPI so your team can push your releases to PyPI, but I was wondering about the following:

1. Currently, I compile the source on the user's machine and this installs all the relevant SWIG interface code to the user. Afterwards, I delete the compiled files, and the python interface is the only thing that remains. Will you make sure the release you push to PyPI just installs the python interface?

2. There is no good way to specify the parameter files, other than the user somehow having to download them separately and point to them to the RNA.read-parameter_file function (apologies if I get the name wrong, it's mentioned in the README with this repo). Can you make sure when the user installs the package, it is as easy as specifying a string to load the parameters?

3. The python interface is now just a SWIG interface to the underlying C code. Will your team spend some time to flesh out a more curated python interface? It'd help if you have a series of documents explaining all the different interface functions, their proper parameters, usage, purpose, return type etc.

Let me know, what you think.
Ayaan

**Comment by AH-Merii** [comment] 2023-06-19 09:19
@RaumZeit @ayaanhossain 

I trust you are both doing well. As a user and enthusiast of the ViennaRNA project, I have been closely following your conversation regarding the Python package support.

Firstly, let me express my heartfelt gratitude for the valuable work you both have done. Ayaan, your initiative to package ViennaRNA for PyPI and maintain it has been of immense value. Ronny, your willingness to take over the PyPI package to provide official updates is a testament to the commitment of the original development team towards the project and its users.

I noticed that it's been a week since your last exchange. As an interested party and a user of the ViennaRNA package, I would like to encourage you both to continue this important conversation. Your ongoing dialogue on this topic is vital for the future development and support of the ViennaRNA Python package.

Furthermore, I am excited to see the integration of GitHub actions into your project pipelines. It would be great to see the Python package become an integral part of the official CI/CD. This would not only ensure the efficient and effective maintenance of the project but would also solidify the trust of the user community in the ViennaRNA package.

Thank you both for your dedication and commitment to this project. I am sure many users like myself eagerly await the outcomes of your ongoing discussion and collaboration.

Looking forward to the continued growth and success of the ViennaRNA project.

Best regards,
Abed

**Comment by RaumZeit** [comment] 2023-06-19 11:16
Hi @ayaanhossain and @AH-Merii ,

I'm pretty busy these days with giving lectures at the university, so I can't dedicate too much time to this project during the next two weeks or so. But, we are still willing to proceed on that matter.
So let me first answer the questions @ayaanhossain mentioned:

1. Sure, for the PyPI version, we will only install the Python interface and no additional other parts of the ViennaRNA Package, That should be easily possible, since we also do that for our binary packages that we distribute for several linux distros.

2. While we ship energy parameter files, those are mostly intended to be used by our executable programs. In our library, we already provide dedicated API functions that load these parameters independently without the need for these files. So, in essence, we already include all parameter files into our library. They have just not been exposed as strings so far but required the call of high-level functions that would load these parameters, e.g. `RNA.params_load_Andronescu2007()` would load the Andronescu et al. 2007 parameter set.
For the next release, I even added support to actually export these parameters as strings that represent the content of the parameter files. Long story short, no parameter files are required for the Python interface, everything is already compiled into the library and available through the API.

3. While we use SWIG to create the Python bindings for the ViennaRNA C-library we add an object oriented layer that transforms many of our C functions to methods of the respective objects in Python. I understand that this renders the available reference manual documentation somewhat useless for the Python user. However, with version 2.6.0 we introduced an automatic conversion of the Doxygen documentation into Python docstrings that, for the most part, recognizes these transformations from functions to methods. This conversion and the creation of docstrings finally allowed us to provide a Python API documentation which will be growing in the future. You can already find the latest documentation at [Read the Docs ](https://viennarna-python.readthedocs.io/)

4. As for the github actions and the creation of the PyPI packages, this is exactly the way we want to go. We want to fully automate the process such that whenever we create a new release, this will trigger a github action that then uploads the required artifacts to PyPI.

That's all for now from my side and I'll be more focused on bringing this project forward in about 2 weeks from now. 

Cheers,
Ronny

**Comment by RaumZeit** [comment] 2023-06-19 11:28
I forgot to mention that for point 3. we plan to eventually merge both of the created documentations into one.

I'm already in the process to transform our doxygen output to sphinx-generated html websites via the breathe bridge. But this is a tedious task that requires many changes in the way we currently document the API. But once this is done, a merge of both the C-API with all its extra descriptions and example codes and the Python documentation we extract from the generated docstrings should be easy to accomplish.

**Comment by AH-Merii** [comment] 2023-06-19 11:30
@RaumZeit 

Thank you for taking the time to provide such a detailed update amidst your busy schedule. It's truly appreciated!

I'm incredibly excited about the upcoming changes you've outlined for the ViennaRNA Python package. The improvements in the PyPI version, API documentation, and the automated CI/CD practices sound very promising.

Looking forward to these developments in the coming weeks. 😁

**Comment by ayaanhossain** [comment] 2023-06-20 18:27
Thank you @AH-Merii for tracking this, and of course thank you @RaumZeit for getting back on this. At this point, I think I am ready to handoff the PyPI namespace to you. The simplest way for me is to add you or someone from your team as the "owner" and at that point you will be able to remove me from the current ownership on PyPI. Let me know the email address of the individual I need to add to the project. I imagine the owner email will need to be registered with PyPI.

I must say Ronny, I've had a great time with ViennaRNA throughout my grad school, and I want to clarify that it was never my intention to maintain anything beyond what TBI was doing, was happy to be just a consumer. Unfortunately, there were issues flagged on the TBI GitHub repo where I and others wanted an easy way to install ViennaRNA for python use, and it seemed at the time a third party was involved in producing the bioconda interface that was not being compatible with updated versions of python (3.8 or maybe 3.9). It was also not great that someone producing a package using the ViennaRNA python interface couldn't ship their package to PyPI and make it easy for the end user (one who downloads and uses the custom package using ViennaRNA) to install ViennaRNA without going through the compilation manually. This repo and the subsequent hosting on PyPI was supposed to mitigate that challenge. I wish you, TBI and ViennaRNA all the best.

Ayaan

**Comment by RaumZeit** [comment] 2023-07-09 13:39
@AH-Merii @ayaanhossain:

Dear Ayaan and Abed,
I started to refactor the Python interface build process for the ViennaRNA Package and everything seems good so far. I use setuptools to build RNAlib and the swig extension and prepare/compile the `sdist` and `bdist_wheel` packages. Now, that I wanted to test whether everything works correctly by pushing it to test.pypi.org, I realized that the `ViennaRNA` project at test.pypi.org is taken by @AH-Merii . I tried reaching out via email a few days ago and today. but didn't get a response yet. That's why I write here now. Would you, @AH-Merii, be so kind to add me to the list of maintainers for your project at test.pypi.org?! This would allow me to generate an API token to upload the artifacts. Otherwise, I'd need to create a package with a different package name that would render testing much more tedious.

As soon as everything looks right, I start the github actions integration via cibuildwheel to build binary packages for Linux, macosx and hopefully windows. Once that also works out as expected, I'd need access to the `ViennaRNA` project at pypi.org from @ayaanhossain . 

Just as a side note, I intend to keep the
```
import ViennaRNA
```
thing next to our official
```
import RNA
```
Both will actually load the same set of functions, classes and variables. Also, the `RNA/__init__.py` now is an actual package description file instead of a copy of the `RNA.py` generated by swig. So, the swig wrapper (`RNA.py`) itself is now an actual module (`RNA.RNA`) and part of the `RNA` package.

For future purposes, I think splitting the library into smaller sub packages is the way to go, e.g.:
```
from ViennaRNA import plotting
````
and things alike. But this requires some more restructuring in the SWIG interfaces and a shared library for `libRNA`.  So, this change will likely come not earlier than version 3.0.0.

Thanks for your understanding and commitment!
Best,
Ronny

**Comment by ayaanhossain** [comment] 2023-07-09 16:50
Hi Ronny, thanks for the initiative. I'm happy to see that you're focusing on a nice python interface for the RNAlib functions. I have added you to the pypi package for ViennaRNA, please feel free to start playing around with it. I have added you as a Maintainer, and once you confirm that you've received the invite, I will promote you to full owner. Best, Ayaan

**Comment by AH-Merii** [comment] 2023-07-10 15:34
@RaumZeit 

Dear Ronny,

Thank you for your message and your continuous efforts on the ViennaRNA project. I apologize for the lack of response to your earlier emails. They were unfortunately automatically flagged as suspicious and were filtered out, which is why I didn't see them sooner.

I appreciate your diligence and hard work in refactoring the Python interface build process. I've looked into your request and am pleased to inform you that I've added you as an owner to the ViennaRNA project at test.pypi.org. You should now be able to generate an API token to upload the artifacts.

Your plan to maintain both the ViennaRNA and RNA imports, as well as your foresight into restructuring the SWIG interfaces and introducing smaller subpackages, is greatly commendable. I fully support your initiative and look forward to seeing these changes implemented in version 3.0.0.

Again, apologies for any inconvenience caused by the delayed response, and thank you for your understanding. 

Best regards,
Abed

**Comment by RaumZeit** [comment] 2023-07-11 13:25
Thanks a lot to the both of you!
I very much appreciate your trust in me/us working on the ViennaRNA Package.

The current state for the PyPI packages is that my pipeline runs fine for Linux and MacOS. For the latter, I was also able to build arm64 wheels today, so they will be included as well. What doesn't work is support for PyPy, since our C Extension doesn't seem compatible with their C layer. Windows builds need some more changes to the source code and will most likely follow in the future, once I find the time to rewrite the upstream code to support building with MSVC. I'll test upload of the sdist and wheel packages to test.pypi.org later this week. 
I'll let you know once the tests for test.pypi.org are successful.

Best,
Ronny

**Comment by RaumZeit** [comment] 2023-07-12 09:28
Yay!

My pipeline successfully published the packages to test.pypi.org!
You can see the result at https://test.pypi.org/project/ViennaRNA/

So, the next step will be to prepare everything for the official PyPI repo.

Cheers,
Ronny

**Comment by RaumZeit** [comment] 2023-07-12 20:51
Well, @ayaanhossain:

My pipelines are set up and working, publishing to both [TestPyPI](https://test.pypi.org/project/ViennaRNA/) and [PyPI](https://pypi.org/project/ViennaRNA/) works (they show version 2.6.0 now) and will be triggered automatically whenever a new release is issued on github. The good thing is that most users might not even have to compile the package, since the new build pipeline already provides Python 3.8 - 3.11 builds for Linux and MacOS X. As mentioned earlier, I'll have a look at Windows builds as well, but this might take some more time as it requires more changes in our code base....

Thanks again for everything! I'll have a look at the content of your git repo later to see which parts might be interesting to keep for the https://viennarna-python.readthedocs.io site. Also I try to add more documentation/examples on the energy parameter settings via the API.

Best,
Ronny

P.S.: you can make me owner of the PyPI project now
P.S.S.: The github actions workflow that builds and publishes everything is in our development branch and will be accessible once the next release is pushed to github. Just in case you are interested. The same is true for the `setup.py`, `setup.cfg` and `pyproject.toml` files I used to create the Python packages (Although they are already included in the `sdist` packages on PyPI)

**Comment by ayaanhossain** [comment] 2023-07-12 21:09
Congrats Ronny! I've promoted you to owner on the PyPI. Thank you and good luck! Hope the new python interface is really pythonic and easy to use for design and evaluation of RNA sequences. Ayaan

**Closed as completed by ayaanhossain** 2023-07-12 21:09 UTC
